### ISSUE TITLE
Possible Bug in Calibration and Visualizer counter

### ISSUE THREAD

**Issue by MichaMans** [RWTH-EBC/AixCaliBuHA#5]
We should maybe switch to one single counter for both, calibration and visualization. Otherwise it might lead to weird bugs. See attached log, where the calibration is at step 1758 and the visualizer at 1760 which leads to errors.

```30.08.2021-11:57:16 INFO Calibrator:      1756   1500.000000    750.000005      2.000000      0.300000      0.559923        -          = 1.0*0.5599
30.08.2021-11:57:23 INFO Calibrator:      1757   1500.000000    750.000000      2.000000      0.300000      0.559923        -          = 1.0*0.5599
30.08.2021-11:57:29 INFO Calibrator:      1758   1500.000000    750.000000      2.000000      0.300000      0.559923        -          = 1.0*0.5599
30.08.2021-11:57:31 INFO Calibrator: 
Results for calibration of model: dhc_models_hassel.GroundHeatExchange.GoundAndPipe.Verification.EmbeddedPipeCalibration
Number of iterations: 1758
Final parameter values:
Iteration   rho           c             ...s_ground   lambda          NRMSE      penaltyfactor   Unweighted NRMSE
     1760   1500.000000    750.000000      2.000000      0.300000      0.559923        -          = 1.0*0.5599

```

[Calibrator.log](https://github.com/RWTH-EBC/AixCaliBuHA/files/7081809/Calibrator.log)

**Comment by tobinfiedler** [comment]
An error caused by the different counters: 
The counter of the iterations actually performed: **25**
The counter that counts each iteration started: **48** 

In the end, the graph of the iteration with the best result should probably be accessed. The graph is searched for with the counter of the started iteration. However, the graphics are saved with the counter of the iterations performed. The result is an error message and a termination of AixCaliBuHA.

> 11.10.2021-11:43:08 INFO MultipleClassCalibrator:        **25**   0.000002   79.930178        -          = 1.0*79.93
> 11.10.2021-11:43:09 INFO MultipleClassCalibrator: 
> Results for calibration of model: BasicModel_CaliAixCalibration.BasicModel_CaliSimulator
> **Number of iterations: 25**
> Final parameter values:
> Iteration   ...Fixed     NRMSE   penaltyfactor   Unweighted NRMSE
>        **48**   0.000002   3.688188        -          = 1.0*3.688
> Traceback (most recent call last):
>   File "C:/Users/sgo-tfi/sciebo2/MA/06_Simulationsmodell/Kalibrierung/main.py", line 28, in <module>
>     main()
>   File "C:/Users/sgo-tfi/sciebo2/MA/06_Simulationsmodell/Kalibrierung/main.py", line 24, in main
>     run_calibration.run_calibration(sim_api=sim_api, cal_classes=calibration_classes, validation_class=validation_class)
>   File "C:\Users\sgo-tfi\sciebo2\MA\06_Simulationsmodell\Kalibrierung\run_calibration.py", line 100, in run_calibration
>     result = modelica_calibrator.calibrate(
>   File "e:\sgotfi\git\aix\aixcalibuha\aixcalibuha\calibration\multi_class_calibrator.py", line 165, in calibrate
>     super().calibrate(framework=framework, method=method, **kwargs)
>   File "e:\sgotfi\git\aix\aixcalibuha\aixcalibuha\calibration\calibrator.py", line 318, in calibrate
>     _res = self.optimize(framework, method, **kwargs)
>   File "e:\sgotfi\git\ebcpy\ebcpy\optimization.py", line 139, in optimize
>     res = minimize_func(method, **kwargs)
>   File "e:\sgotfi\git\ebcpy\ebcpy\optimization.py", line 298, in _scipy_differential_evolution
>     self._handle_error(error)
>   File "e:\sgotfi\git\aix\aixcalibuha\aixcalibuha\calibration\calibrator.py", line 437, in _handle_error
>     self.logger.save_calibration_result(best_iterate=self._current_best_iterate,
>   File "e:\sgotfi\git\aix\aixcalibuha\aixcalibuha\utils\visualizer.py", line 500, in save_calibration_result
>     copyfile(bestgoal, f'{iterpath}\\best_goals.%s' % self.file_type)
>   File "C:\Users\sgo-tfi\.conda\envs\py38_ebcpyNew\lib\shutil.py", line 264, in copyfile
>     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
**> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sgo-tfi\\sciebo2\\MA\\06_Simulationsmodell\\Kalibrierung\\results_p_IT50\\Constant1_20_30_2_100_550_650\\TimeSeriesPlot\\48_goals.png'**
> 11.10.2021-11:43:09 INFO DymolaAPI: Closing Dymola
> 11.10.2021-11:43:10 INFO DymolaAPI: Successfully closed Dymola
> Process finished with exit code 1
